export const data = [
    {
        id: "1",
        name: "Ananas",
        image: "/_data/ananas.png",
        price: "2,70",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "2",
        name: "Apfel",
        image: "/_data/apfel.png",
        price: "1,77",
        kind: "Obst",
        quantity: "1kg",
    },
    {
        id: "3",
        name: "Aprikose",
        image: "/_data/aprikose.png",
        price: "0,40",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "4",
        name: "Bananen",
        image: "/_data/bananen.png",
        price: "1,20",
        kind: "Obst",
        quantity: "1kg",
    },
    {
        id: "5",
        name: "Birne",
        image: "/_data/birne.png",
        price: "0,90",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "6",
        name: "Brombeeren",
        image: "/_data/brombeeren.png",
        price: "2,40",
        kind: "Obst",
        quantity: "100g",
    },
    {
        id: "7",
        name: "Cranberries",
        image: "/_data/cranberries.png",
        price: "2,10",
        kind: "Obst",
        quantity: "100g",
    },
    {
        id: "8",
        name: "Datteln",
        image: "/_data/datteln.png",
        price: "1,70",
        kind: "Obst",
        quantity: "1kg",
    },
    {
        id: "9",
        name: "Erdbeeren",
        image: "/_data/erdbeeren.png",
        price: "3,20",
        kind: "Obst",
        quantity: "100g",
    },
    {
        id: "10",
        name: "Feige",
        image: "/_data/feige.png",
        price: "1,70",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "11",
        name: "Granatapfel",
        image: "/_data/granatapfel.png",
        price: "2,90",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "12",
        name: "Grapefruit",
        image: "/_data/grapefruit.png",
        price: "1,90",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "13",
        name: "Heidelbeeren",
        image: "/_data/heidelbeeren.png",
        price: "2,20",
        kind: "Obst",
        quantity: "100g",
    },
    {
        id: "14", ///// Probleme
        name: "Himbeeren",
        image: "/_data/himbeeren.png",
        price: "2,20",
        kind: "Obst",
        quantity: "100g",
    },
    {   //HIER BIN ICH HIER BIN ICH HIER BIN ICH
        id: "15",
        name: "Johannisbeeren",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "16",
        name: "Kirschen",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "17",
        name: "Kiwi",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "18",
        name: "Limette",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "19",
        name: "Litschi",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "20",
        name: "Mandarine",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "21",
        name: "Mango",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "22",
        name: "Melone",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "23",
        name: "Mirabelle",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "24",
        name: "Orange",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "25",
        name: "Papaya",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "26",
        name: "Pfirsich",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "27",
        name: "Pflaume",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "28",
        name: "Preiselbeeren",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "29",
        name: "Pomelo",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "30",
        name: "Quitten",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "31",
        name: "Rhabarber",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "32",
        name: "Sanddorn",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "33",
        name: "Stachelbeeren",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "34",
        name: "Weintrauben",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "35",
        name: "Zitrone",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    },
    {
        id: "36",
        name: "Zwetschge",
        image: "/_data/ananas.png",
        price: "1,30",
        kind: "Obst",
        quantity: "1 Stück",
    }
]