export const data = [
    {
        id: "1",
        name: "Ananas",
        image: "./ananas.png",
        price: "2,70€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "2",
        name: "Apfel",
        image: "./apfel.png",
        price: "1,77€",
        kind: "fruit",
        quantity: "1kg",
    },
    {
        id: "3",
        name: "Aprikose",
        image: "./aprikose.png",
        price: "0,40€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "4",
        name: "Bananen",
        image: "./bananen.png",
        price: "1,20€",
        kind: "fruit",
        quantity: "1kg",
    },
    {
        id: "5",
        name: "Birne",
        image: "./birne.png",
        price: "0,90€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "6",
        name: "Brombeeren",
        image: "./brombeeren.png",
        price: "2,40€",
        kind: "fruit",
        quantity: "100g",
    },
    {
        id: "7",
        name: "Cranberries",
        image: "./cranberries.png",
        price: "2,10€",
        kind: "fruit",
        quantity: "100g",
    },
    {
        id: "8",
        name: "Datteln",
        image: "./datteln.png",
        price: "1,70€",
        kind: "fruit",
        quantity: "1kg",
    },
    {
        id: "9",
        name: "Erdbeeren",
        image: "./erdbeeren.png",
        price: "3,20€",
        kind: "fruit",
        quantity: "100g",
    },
    {
        id: "10",
        name: "Feige",
        image: "./feige.png",
        price: "1,70€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "11",
        name: "Granatapfel",
        image: "./granatapfel.png",
        price: "2,90€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "12",
        name: "Grapefruit",
        image: "./grapefruit.png",
        price: "1,90€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "13",
        name: "Heidelbeeren",
        image: "./heidelbeeren.png",
        price: "2,20€",
        kind: "fruit",
        quantity: "100g",
    },
    {
        id: "1", ///// Probleme
        name: "Himbeeren",
        image: "./himbeeren.png",
        price: "2,20€",
        kind: "fruit",
        quantity: "100g",
    },
    {   //HIER BIN ICH HIER BIN ICH HIER BIN ICH
        id: "14",
        name: "Johannisbeeren",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "15",
        name: "Kirschen",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "16",
        name: "Kiwi",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "17",
        name: "Limette",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "18",
        name: "Litschi",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "19",
        name: "Mandarine",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "20",
        name: "Mango",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "21",
        name: "Melone",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "22",
        name: "Mirabelle",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "23",
        name: "Orange",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "24",
        name: "Papaya",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "25",
        name: "Pfirsich",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "26",
        name: "Pflaume",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "27",
        name: "Preiselbeeren",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "28",
        name: "Pomelo",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "29",
        name: "Quitten",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "30",
        name: "Rhabarber",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "31",
        name: "Sanddorn",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "32",
        name: "Stachelbeeren",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "33",
        name: "Weintrauben",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "34",
        name: "Zitrone",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    },
    {
        id: "35",
        name: "Zwetschge",
        image: "./ananas.png",
        price: "1,30€",
        kind: "fruit",
        quantity: "1 Stück",
    }
]